name: Changelog

on:
  workflow_dispatch:
  # Trigger analysis when pushing in master or pull requests,
  # and when creating a pull request.
  release:
    types:
      - created

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        with:
          from-tag: v1.0.3
          to-tag: HEAD